name : CI/CD Pipeline


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Build and Push Docker Image
        run: |
          docker build -t smmota/thenewyorktimesapi:latest .
          docker push smmota/thenewyorktimesapi:latest

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          version: 1.21.0

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml