name : "3 - [PROD] Build, Test & Publish"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Build
        run: dotnet build

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Publicar aplicação
        run: dotnet publish -c Release -o ./publish

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          version: 1.21.0
          
      - name: Fazer login no registro Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construir imagem Docker
        run: docker build -t smmota/thenewyorktimesapi:latest .
        
      - name: Publicar imagem Docker
        run: docker push smmota/thenewyorktimesapi:latest

      - name: Listar arquivos no diretório
        run: |
          echo "Executando dir..."
          dir      

      - name: Implantação no Kubernetes
        run: kubectl apply -f deployment.yaml
