name: "2 - [DEV] Build, Test & PR"

on:
  push:
    branches:
      - develop
 
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código 
        uses: actions/checkout@v2
            
      - name: Restaurar pacotes
        run: dotnet restore

      - name: Build
        run: dotnet build
        
  tests:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: dotnet test