name: "2 - [DEV] Build, Test & PR"

on:
  pull_request:
    branches:
      - develop
 
permissions:  
  pull-requests: write  

jobs:
  ci-dotnet-core:
    name: ci-dotnet-core
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código 
        uses: actions/checkout@v2
            
      - name: Restaurar pacotes
        run: dotnet restore

      - name: Build
        run: dotnet build
        
      - name: Test
        run: dotnet test

  open-pr-to-production:    
    name: open-pr-to-production
    runs-on: ubuntu-latest
    needs: ci-dotnet-core 
    
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6  
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Este pull request foi aberto automaticamente pelo GitHub Actions.
          title: Pull Request To Develop
          body: PR aberto automaticamente
          branch: main